module.exports = [
  require('./home'),
  require('./payment-processor'),
  require('./public'),
  require('./charge'),
  require('./login-github'),
  require('./create-profile'),
  require('./new-user-home'),
  require('./returning-user-home'),
  require('./donation-one-off'),
  require('./donation-regular'),
  require('./profile-select-cohort'),
  require('./profile-select-relation'),
  require('./profile-complete'),
  require('./donation-first-time-user'),
  require('./lets-get-started'),
  require('./display-donations'),
];
